sources:
  - name: accesstime
    handler:
      graphql:
        endpoint: https://api.studio.thegraph.com/query/77391/accesstime/version/latest
        retry: 2
        timeout: 5000
plugins:
  - pollingLive:
      defaultInterval: 1000
documents:
  - './src/**/*.graphql'